### ISSUE TITLE
Shopping list with uft8 chars - problems printing

### ISSUE THREAD

**Issue by marmistrz** [thinkle/gourmet#800] opened 2015-06-05 20:00 UTC
1. Add ingredients which have not purely Latin chars, e.g. `ser biały`
2. Add them to the shopping list, print it (to file)
3. Black squares appear.

using version 0.17.4-1

**Comment by ockham** [comment] 2015-06-05 21:15
Duplicate of #729.

**Closed by ockham** 2015-06-05 21:15 UTC

**Comment by krzyklo** [comment] 2020-04-10 09:32
Same problem
