### ISSUE TITLE
Invalid Input. Time must be expressed in hours, minutes, seconds etc.

### ISSUE THREAD

**Issue by Maltavius** [thinkle/gourmet#788] opened 2015-02-09 14:46 UTC
I'm typing 24 hours, 48 hours, 24h, 48 h, 24 days, 3600 minutes. All I get is the above error.
![image](https://cloud.githubusercontent.com/assets/10133945/6108360/a64d5170-b072-11e4-890f-f2c6a12cbbe4.png)

I'm unable to edit and or add any new recepies to my database that I imported from linux into the windows version of Gourmet Recepie Manager.

I've tried uninstalling and clearing out %appdata%/Roaming/Gourmet but it doesn't work.
Either my database is corrupt somehow or GRM has a serious bug.

Database is available on request.,

**Comment by ockham** [comment] 2015-03-21 23:12
Duplicate of #781

**Closed by ockham** 2015-03-21 23:12 UTC
Labels: bug, windows
