### ISSUE TITLE
Support for multiple categories per recipe

### ISSUE THREAD

**Issue by apastuszak** [thinkle/gourmet#805] opened 2015-06-14 20:42 UTC
I would love it if Gourmet supported tagging recipes, so I can mark something as dinner, and beef.

**Comment by ockham** [comment] 2015-09-19 12:42
Closing as duplicate of #79 

As a workaround,

> You can use categories as tags -- just separate your categories with commas.

**Closed by ockham** 2015-09-19 12:42 UTC
