### ISSUE TITLE
gourmet: reccard.py:2617:changeUnit:KeyError: 'ingkey'

### ISSUE THREAD

**Issue by codergeek42** [thinkle/gourmet#837] opened 2016-01-17 04:48 UTC
Fedora bug report: https://bugzilla.redhat.com/1228806

Hello. I maintain the Gourmet package in Fedora and one of our users posted a bug which I have been able to reproduce as follows:

(1) Create a new recipe
(2) Add an ingredient
(3) Click the Unit entry for this ingredient but do not select anything from the drop-down
(4) Click into the Amt column for this ingredient

It then gives the following traceback:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gourmet/reccard.py", line 2396, in ingtree_edited_cb
    amt,msg=self.changeUnit(text,self.ingController.get_rowdict(iter))
  File "/usr/lib/python2.7/site-packages/gourmet/reccard.py", line 2617, in changeUnit
    key=ingdict['ingkey']
KeyError: 'ingkey'

I added a print statement just at the beginning of the changeUnit function there which shows that when it is called here, new_unit is an empty string and ingdict is the dictionary:  {'amount': '', 'item': '', 'optional': False, 'unit': None}

**Comment by thinkle** [comment] 2016-01-17 14:31
Ok -- Just reproduced. This is a very odd use case -- adding an empty ingredient, and then editing one piece at a time. I fixed by allowing this use case, but I'm tempted to change the UI to grey out "Add Ingredient" until you've typed something into the text box there. Do you that that might be the better solution (i.e. make it clear how the interface is supposed to work rather than allowing for a clunky/ineffective way of using it?)

Here's my concern: if users think that you're supposed to click Add, then awkwardly click through amounts units and items, then the interface will be pretty horrible -- much worse than typing through a spreadsheet since typing in the listview really isn't that elegant an interface.

In fact, one of the main reasons I built Gourmet was that I couldn't stand the clunky ingredient entry on alternative programs -- I'm a blazing fast typist and I don't believe in looking away from a book when I'm typing to fiddle with the computer. Gourmet lets you just type in ingredients and hit return and it will do all the categorization for you. The only reason you can edit the listview at all is that you need to fix categorization errors, which will inevitably happen (there are way too many variations in the ways people type ingredients for me to handle them all)

**Closed** 2016-01-17 14:33 UTC

**Comment by codergeek42** [comment] 2016-01-17 19:40
I'm no UI expert but I think greying out the box until you've added something is a better long-term solution, as (like you say) it clarifies how the interface is supposed to be used; but being robust enough to handle this particular use case (at least, tolerate without error) is also necessary.

Thanks for making Gourmet and thanks for quickly patching this little issue! :)
